version: '3'

volumes:
  postgres_volume:
  prometheus_data:
  grafana_data:

services:
  app:
    container_name: chat_app
    image: "${REGISTRY}/${IMAGE_NAME}:${TAG_NAME}"
    ports:
      - "${GRPC_PORT_EXTERNAL}:${GRPC_PORT}"
    entrypoint: ["/root/entrypoint.sh"]
    volumes:
      - ${SERVICE_PATH}/.env:/root/.env
    profiles:
      - server
  postgres:
    container_name: chat_pg
    image: postgres:15.4
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    profiles:
      - server
      - local
  prometheus:
    image: prom/prometheus:v2.37.9
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus
    profiles:
      - server
      - local

  grafana:
    image: grafana/grafana-oss:10.0.3
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    profiles:
      - server
      - local
  jaeger:
    image: jaegertracing/all-in-one:1.48
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" # web
      - "14268:14268"
      - "9411:9411"
    profiles:
      - server
      - local